Traceback (most recent call last):
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "aurelio/__main__.py", line 26, in <module>
    main()
  File "aurelio/__main__.py", line 23, in main
    portion)
  File "aurelio/experiment.py", line 124, in run_kfold
    elmo)
  File "aurelio/experiment.py", line 62, in run_train
    main()
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
    args.force)
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/site-packages/allennlp/commands/train.py", line 136, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/site-packages/allennlp/commands/train.py", line 174, in train_model
    check_for_gpu(cuda_device)
  File "/home/helio/miniconda3/envs/allen/lib/python3.7/site-packages/allennlp/common/checks.py", line 58, in check_for_gpu
    raise ConfigurationError("Experiment specified a GPU but none is available;"
allennlp.common.checks.ConfigurationError: "Experiment specified a GPU but none is available; if you want to run on CPU use the override 'trainer.cuda_device=-1' in the json config file."
